
image: ubuntu:24.04

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - sh scripts/az-storage-replace-dir.sh -n tkutchercomdevwa01 -k $AZURE_STORAGE_ACCOUNT_KEY -s src -d "" -c "$web"
  only:
    - main

