image: nikolaik/python-nodejs:latest

stages:
  - build
  - deploy

build:
  stage: build
  artifacts:
    paths:
      - .dist/
  script:
    - ./scripts/build.sh
    - mkdir -p .dist/
    - cp -r dist/tkutcher-dot-com/browser/* .dist/

deploy:
  stage: deploy
  needs:
    - build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  before_script:
    - pip install awscli
  script:
    - cd .dist
    - aws s3 sync . s3://${S3_BUCKET_NAME} --delete
