
stages:
  - deploy

deploy:
  stage: deploy
  image: mcr.microsoft.com/azure-cli:azurelinux3.0
  script:
    - ./scripts/az-storage-replace-dir.sh -n tkutchercomdevwa01 -k "$AZURE_STORAGE_ACCOUNT_KEY" -s src -d ""
  only:
    - main

